title: Sanjay Kumar
logo: "assets/images/logo.jpg"

description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page. I am passionate about AI, ML, and Data Engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanjaybhattoo.github.io" # the base hostname & protocol for your site

 
show_downloads : false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
